# You Podfile should look similar to this file. React Native currently does not support use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'AirSuperViseRN' do
  # Fixes required for pod specs to work with rn 0.42

  pod 'IQKeyboardManager'
  pod 'BaiduMapKit' #百度地图SDK

# when not using frameworks  we can do this instead of including the source files in our project (1/4):
#  pod 'react-native-maps', path: '../../'
#  pod 'react-native-google-maps', path: '../../'  # <~~ if you need GoogleMaps support on iOS
end
